# Generated by Django 5.1.4 on 2025-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(default=5)),
                ('nums_top', models.JSONField()),
                ('nums_left', models.JSONField()),
                ('grid', models.JSONField()),
            ],
        ),
    ]
